### PR TITLE
handle previously build mine

### PR DESCRIPTION
**Pull request by 22PoojaGaur**
Hi,
I have made the changes and tested locally.
It just uses cargoDeployRemote task when re-building the mine.

### CODE REVIEW

**Comment by 22PoojaGaur** [comment]
Sorry, I went in wrong direction while debugging something.
I was pushing to master to check the effect. That is why there are so many commits.
I hope you do a squash merge!

**Comment by 22PoojaGaur** [comment]
@uosl @leoank

**Comment by heralden** [comment]
I just tested this and it works great! :+1: 

I think we can clean it up a bit before merging. Can you remove the debug logging (basically all the `echo` that don't include `$(date)`)? Once that is done, I'll do a squash and merge.

**Comment by 22PoojaGaur** [comment]
@uosl done!

**Review by heralden — APPROVED** [review]
Thanks! Looks good now. [=

**Pull request merged**
